# Generated by Django 4.2.5 on 2023-09-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_post_createdby_post_updatedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updateAt',
            new_name='updatedAt',
        ),
    ]
