# Generated by Django 4.2.5 on 2023-09-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_rename_updateat_post_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoryKey',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tagKey',
        ),
    ]
