# Generated by Django 4.2.5 on 2023-09-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_post_createdby_alter_post_updatedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('typeProject', models.CharField(choices=[('P', 'Pessoal'), ('C', 'Cliente')], max_length=1)),
                ('pictures', models.ImageField(blank=True, default='', upload_to='projects/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Portfolio_Project',
                'verbose_name_plural': 'Portifolio_Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectsLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2048, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkProject', to='Core.portfolioprojects')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tite', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.portfolioprojects')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portifolios',
            },
        ),
    ]
