# Generated by Django 4.2.5 on 2023-09-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_portfolioprojects_projectslinks_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='tite',
            new_name='title',
        ),
    ]
