# Generated by Django 4.2.5 on 2023-09-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_remove_portfolio_project_portfolioprojects_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprojects',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolioProject', to='Core.portfolio'),
        ),
    ]
