# Generated by Django 4.2.5 on 2023-09-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_portfolio_slug_portfolioprojects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprojects',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
