# Generated by Django 4.2.5 on 2023-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_portfolioprojects_ispublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprojects',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolioprojects',
            name='descriptionBody',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolioprojects',
            name='descritptionCard',
            field=models.CharField(default='', max_length=512),
        ),
    ]
