# Generated by Django 4.2.5 on 2023-09-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_rename_descritptioncard_portfolioprojects_descriptioncard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
