# Generated by Django 4.2.5 on 2023-09-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=255)),
                ('showHeader', models.BooleanField(default=True)),
                ('showSearch', models.BooleanField(default=True)),
                ('showMenu', models.BooleanField(default=True)),
                ('showDescription', models.BooleanField(default=True)),
                ('showPagination', models.BooleanField(default=True)),
                ('showFooter', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
            },
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='new_tab',
            new_name='newTab',
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='url_or_path',
            new_name='urlOrPath',
        ),
    ]
