# Generated by Django 4.2.5 on 2023-09-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0003_alter_sitesetup_options_menulink_sitesetup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='newTab',
            new_name='new_Tab',
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='siteSetup',
            new_name='site_Setup',
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='urlOrPath',
            new_name='url_Or_Path',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showDescription',
            new_name='show_Description',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showFooter',
            new_name='show_Footer',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showHeader',
            new_name='show_Header',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showMenu',
            new_name='show_Menu',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showPagination',
            new_name='show_Pagination',
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='showSearch',
            new_name='show_Search',
        ),
    ]
