# Generated by Django 4.2.5 on 2023-09-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0004_rename_newtab_menulink_new_tab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favIcon',
            field=models.ImageField(blank=True, default='', upload_to='media/favicon/%Y/%m/'),
        ),
    ]
