# Generated by Django 4.2.5 on 2023-09-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0005_sitesetup_favicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='favIcon',
            new_name='fav_icon',
        ),
    ]
