# Generated by Django 4.2.5 on 2023-09-16 16:42

from django.db import migrations, models
import utils.modelValidator


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0006_rename_favicon_sitesetup_fav_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='blog_description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='fav_icon',
            field=models.ImageField(blank=True, default='', upload_to='favicon/%Y/%m/', validators=[utils.modelValidator.validatePng]),
        ),
    ]
