# Generated by Django 4.2.5 on 2023-09-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0007_sitesetup_blog_description_alter_sitesetup_fav_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='description',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_2',
            field=models.CharField(default='', max_length=512),
        ),
    ]
