# Generated by Django 4.2.5 on 2024-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0008_remove_sitesetup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_3',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_4',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_5',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_images',
            field=models.ImageField(default='pic_index', upload_to='pics_index'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='title_2',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='title_3',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='title_4',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='index_description_1',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='index_description_2',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
