# Generated by Django 4.2.5 on 2024-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0009_sitesetup_index_description_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='index_images',
        ),
    ]
