# Generated by Django 4.2.5 on 2024-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0010_remove_sitesetup_index_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetupPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(default='pic', upload_to='pics_index')),
            ],
        ),
    ]
