# Generated by Django 4.2.5 on 2024-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0013_sitesetup_index_description_4_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_5_1',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='index_description_5_2',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
